### Base URL
@baseUrl = http://localhost:8085

### Search default limit
GET http://localhost:8085/api/v2/products?search=iphone

### Custom limit
GET http://localhost:8085/api/v2/products?search=iphone&limit=5

### Invalid limit
GET http://localhost:8085/api/v2/products?limit=abc

### Over max limit
GET http://localhost:8085/api/v2/products?limit=1000

###
GET http://localhost:8085/api/v2/categories/php

###
GET http://localhost:8085/api/v2/categories/java


### Valid slug
GET http://localhost:8085/api/v2/products/iphone-15-pro

### Invalid slug
GET http://localhost:8085/api/v2/products/Iphone@123


### Valid UUID
GET http://localhost:8085/api/v2/users/550e8400-e29b-41d4-a716-446655440000


### Invalid UUID
GET http://localhost:8085/api/v2/users/123


###
GET {{baseUrl}}/api/v2/users


### ----------------------------------------
### Health Check
GET {{baseUrl}}/
Accept: application/json


### ----------------------------------------
### Example POST (if later you add API)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Thinh",
  "email": "thinh@example.com"
}
