### Base URL
@baseUrl = http://localhost:8085
@apikey = my-super-secret-key

###
GET http://localhost:8085/uploads/3b964877-effc-4853-ab7c-9da229c4e58a.png



### Upload Category
POST {{baseUrl}}/api/v2/categories/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Technology
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="is_active"

true
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
POST {{baseUrl}}/api/v2/categories
Content-Type: application/x-www-form-urlencoded
x-api-key: {{apikey}}

name=Technology&description=Tech category&is_active=true


###
POST {{baseUrl}}/api/v2/products
Content-Type: application/json
x-api-key: {{apikey}}

{
  "name": "iPhone 15",
  "slug": "iphone-15",
  "price": 999.99,
  "category": "golang",
  "description": "Latest Apple product",
  "is_active": true,
  "images": [
    {
      "link": "https://example.com/iphone."
    },
    {
      "link": "https://example.com/iphone1.jpg"
    }
  ]
}


###
POST {{baseUrl}}/api/v2/products
Content-Type: application/json

{
  "name": "a",
  "slug": "IPHONE",
  "price": -5,
  "category": "java",
  "is_active": false
}



###
GET http://localhost:8085/api/v2/news
x-api-key: {{apikey}}

###
GET http://localhost:8085/api/v2/news/golang-1-22-released


### Search default limit
GET http://localhost:8085/api/v2/products?search=iphone

### Custom limit
GET http://localhost:8085/api/v2/products?search=iphone&limit=101

### Invalid limit
GET http://localhost:8085/api/v2/products?limit=abc

### Over max limit
GET http://localhost:8085/api/v2/products?limit=1000

###
GET http://localhost:8085/api/v2/categories/php

###
GET http://localhost:8085/api/v2/categories/java


### Valid slug
GET http://localhost:8085/api/v2/products/iphone-15-pro

### Invalid slug
GET http://localhost:8085/api/v2/products/Iphone@123


### Valid UUID
GET http://localhost:8085/api/v2/users/550e8400-e29b-41d4-a716-446655440000


### Invalid UUID
GET http://localhost:8085/api/v2/users/123


###
GET {{baseUrl}}/api/v2/users


### ----------------------------------------
### Health Check
GET {{baseUrl}}/
Accept: application/json


### ----------------------------------------
### Example POST (if later you add API)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Thinh",
  "email": "thinh@example.com"
}
